### ISSUE TITLE
Shouldn't there be src instead of dst?

### ISSUE THREAD

**Issue by alexey-pelykh** [PeculiarVentures/xmldsigjs#16]
@microshine 
https://github.com/PeculiarVentures/xmldsigjs/blob/c20f283bbf4d7d0761c298189a7755a00ab2a704/src/signed_xml.ts#L138

**Comment by microshine** [comment]
I think you are too close. I think `FixupNamespaceNodes` must be fixed

`FixupNamespaceNodes` uses only `XmlCode.SelectNamespaces`, but maybe `SelectRootNamespaces` should be added too

SelectRootNamespaces - returns list of namespaces form parent nodes.
https://github.com/PeculiarVentures/xmldsigjs/blob/c20f283bbf4d7d0761c298189a7755a00ab2a704/src/signed_xml.ts#L578

I'll test it a bit later. I have to finish some tasks before
