### ISSUE TITLE
Unclear issue with #Digest()

### ISSUE THREAD

**Issue by alexey-pelykh** [PeculiarVentures/xmldsigjs#19]
@microshine https://github.com/PeculiarVentures/PKI.js/issues/136#issuecomment-346923330
`Digest()` accepted both 
```
const sha1 = xmldsigjs.CryptoConfig.GetHashAlgorithm('SHA-1')
const issuerNameHash = await sha1.Digest(Buffer.from(new Uint8Array(publicCertificateInfo.issuer.valueBeforeDecode)))
```
and
```
const sha1 = xmldsigjs.CryptoConfig.GetHashAlgorithm('SHA-1')
const issuerNameHash = await sha1.Digest(publicCertificateInfo.issuer.valueBeforeDecode)
```
yet gave completely different results and didn't complain, while
```
const issuerNameHash = crypto.createHash('sha1')
  .update(Buffer.from(new Uint8Array(publicCertificateInfo.issuer.valueBeforeDecode)))
  .digest()
```
complained about raw `publicCertificateInfo.issuer.valueBeforeDecode`

any insights what was going on?

**Comment by microshine** [comment]
@alexey-pelykh I think problem is here https://github.com/PeculiarVentures/xmldsigjs/blob/master/src/algorithm.ts#L30

publicCertificateInfo.issuer.valueBeforeDecode returns ArrayBuffer, but Digest method needs Uint8Array

I'll update Digest method

**Comment by microshine** [comment]
@alexey-pelykh xmldsigjs@2.0.17 is available
