### ISSUE TITLE
Signature location

### ISSUE THREAD

**Issue by Ameb** [PeculiarVentures/xmldsigjs#24]
I'm trying to use `xmldsigjs` to sign some xml files with nodejs. If i haven't missed something the `<Signature>` node is always located under the root element:
```xml
<Root>...document...<Signature></Signature></Root>
```
I wonder if the API allows to ~move~ return the signature element. We have to verify some documents and the signature must be located on a determined path. If not, would it be possible to get the signature 
and place it manually or move it after sign? 

```xml
<Root><SomeContainer>...<Signature></Signature></SomeContainer>...</Root>
```

**Comment by microshine** [comment]
You can covert Signature to XmlElement
```js
xmldsig.Sign(algorithm, privateKey, parsedXml, options)
  .then((signature) => {
    const xmlSignature = signature.GetXml(); // XmlElement
    yourXmlNode.append(xmlSignature);
    console.log("Output:", new XMLSerializer(). serializeToString(yourXmlNode));
  })
```

**Comment by Ameb** [comment]
Exactly what I was looking 😀
