### ISSUE TITLE
How to use new XmlDSigJs.SignedXml()?

### ISSUE THREAD

**Issue by erickod** [PeculiarVentures/xmldsigjs#29]
I'm trying using the method new XmlDSigJs.SignedXml(), but yet I'm passing parameters e properties like 'name' and even so I'm receiving '(node:26652) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'name' of undefined' as return. Could someone help with that?

**Comment by rmhrisk** [comment]
Did you get this working?

**Comment by erickod** [comment]
Sure. Now it's working fine. A bit of hard work it's good, isn't?

But thanks anyway!

Em qua, 19 de set de 2018 03:04, Ryan Hurst <notifications@github.com>
escreveu:
