### ISSUE TITLE
problems compiling with typescript

### ISSUE THREAD

**Issue by jupa1986** [PeculiarVentures/xmldsigjs#57]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

I have a problem compiling this library with typescript backend (nestjs) 

node_modules/xmldsigjs/build/types/xml/key_infos/x509_data.d.ts:58:9 - error TS2611: 'Key' is defined as a property in class 'KeyInfoClause', but is overridden here in 'KeyInfoX509Data' as an accessor.

temporary I add the following comment in the file x509_data.d.ts

// @ts-nocheck

**Comment by microshine** [comment]
Try `skipLibCheck` option.

https://www.typescriptlang.org/tsconfig#skipLibCheck

**Comment by gwynjudd** [comment]
> Try skipLibCheck option.

Hello @microshine this seems like a fine enough resolution.

But I'm wondering if it will be acceptable to put a PR to resolve this by removing the get accessor for `Key` and the `key` property on `KeyInfoX509Data`? Typescript 4.x has intentionally made this an error (https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-0.html#properties-overriding-accessors-and-vice-versa-is-an-error). Please let me know your thoughts.

**Comment by lrivera-verimatrix** [comment]
I am also facing this problem and I see the workaround. However, would this be fixed in this library in the future?

Thans in advance!

**Comment by microshine** [comment]
The new version `xmldsigjs@2.5.1` has been published. Please try it

**Comment by lrivera-verimatrix** [comment]
Works, thanks a lot 👍
